### ISSUE TITLE
Update UTD Grades data for fall 2020, spring 2021, and summer 2021 semesters

### ISSUE THREAD

**Issue by WillieCubed** [UTDNebula/utd-grades#18]
# Overview

The UTD Grades database needs to be updated to display grade distributions for fall 2020, spring 2021, and summer 2021 data. Using the data that @Tmtomer and the Mercury have obtained using a Freedom of Information Act request, follow the repository's documentation on uploading the grades data to the database on AWS that currently stores grades data.

**Comment by CharlieMahana** [comment]
There was an inconsistency with how administration had provided data. The `main.py` converter file changes "Course Number" to "num" while administration provided data contained "Course\nNumber" instead. A quick find and replace all fixes this error.

Additionally, the Connection class is imported into index.js within loader but never calls the connect method. Calling this method fixes the database connection error.

**Comment by WillieCubed** [comment]
@CharlieMahana are we all good to close this?

**Comment by WillieCubed** [comment]
Closed by 56e1cd0c12479343611aa6e4ac04f32d5a326c65
